# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

lang:                en

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-image-size]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Tyler Sengia's Blog"
description:	       'Web, DevOps, IoT, tutorials, and examples.'
author:              'Tyler Sengia'

url: https://www.tsengia.net

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false